version: "3.9"
   
services:
  postgres-01:
    image: postgres:13.3
    volumes:
      - postgres-01-data:/var/lib/postgresql/data
  postgres-02:
    image: postgres:13.3
    volumes:
      - postgres-02-data:/var/lib/postgresql/data
  postgres-03:
    image: postgres:13.3
    volumes:
      - postgres-03-data:/var/lib/postgresql/data
volumes:
  postgres-01-data:
  postgres-02-data:
  postgres-03-data: