version: "3.9"
   
services:
  postgres-01:
    container_name: postgres-01
    build: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres-01
    volumes:
      - postgres-01-data:/var/lib/postgresql/data
  postgres-02:
    container_name: postgres-02
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres-02
    volumes:
      - postgres-02-data:/var/lib/postgresql/data
  postgres-03:
    container_name: postgres-03
    build: .
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres-03
    volumes:
      - postgres-03-data:/var/lib/postgresql/data

volumes:
  postgres-01-data:
  postgres-02-data:
  postgres-03-data: